name: Unit Tests

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.11

        - name: Install dependencies
          env:
            LUMBERJACK_MODELS_TOKEN: ${{ secrets.LUMBERJACK_MODELS_TOKEN }}
          run: |
            python -m pip install --upgrade pip
            pip install -e .

        - name: Run tests
          run: |
            python -m unittest discover -v -s ./tests -p *_test.py